broadinstitute/gnomad_qc

variant_qc/create_ranked_scores.py

- Updated clinvar expression to match current clinvar HT format
- Added de novo counts outside of LCRs

Small changes in rank scores creation

---

load_data/load_coverage.py
variant_qc/exomes_genomes_coverage.py

- Optimized coverage loading expressions (much faster!)
- Added exomes/genomes coverage stats computation script

Coverage import and analysis

---

gnomad_qc/v2/resources/annotations.py

These annotations where in gnomad_hail but are private so should be moved to the gnomad_qc/v2 repo

Moved private gnomAD resources from gnomad_hail

---

.github/workflows/ci.yml

Fix issues seen in https://github.com/broadinstitute/gnomad_qc/pull/48/checks?check_run_id=999737932

Install wheel in CI workflow

---

gnomad_qc/v2/resources/basics.py
gnomad_qc/v3/load_data/compute_coverage.py

And small compute efficiency improvement

Updated coverage version

---

gnomad_qc/v3/annotations/generate_qc_annotations.py

See https://github.com/broadinstitute/gnomad_methods/pull/258 for necessary change in gnomad_methods.

Reduce memory usage of `compute_info`

---

gnomad_qc/v3/resources/sample_qc.py
gnomad_qc/v3/sample_qc/sample_qc.py

Untested, but wanted to get it looked at before I get to that point

Add inbreeding sample qc calculation using population AF

---

gnomad_qc/v2/variant_qc/prepare_data_release.py

This was causing import issues. Did not fix anything else in this script

Fixed slack import in v2 prepare data release

---

gnomad_qc/v2/resources/basics.py

Updated the public path functions to point to the google hosted HTs.

Updated v2 public paths

---

gnomad_qc/v3/annotations/generate_freq_data.py
gnomad_qc/v3/resources/basics.py

Changes to the frequency code to allow for multiple subsets to be passed, this is needed for the HGDP + TGP subset, but is also good to have in place if we want other subset combinations in the future

Hgdp tgp freq mod

---

gnomad_qc/v2/load_data/import_gnomad_sv.py
gnomad_qc/v2/load_data/import_resources.py
gnomad_qc/v2/resources/basics.py
gnomad_qc/v2/resources/variant_qc.py
gnomad_qc/v2/sample_qc/get_topmed_dups.py
gnomad_qc/v2/variant_qc/exomes_genomes_coverage.py
gnomad_qc/v3/resources/sample_qc.py
gnomad_qc/v4/resources/sample_qc.py

Some of these paths are for old release work that won't be re-run, but I figured it was worth trying to track and update the paths that we know about. (Some of the ones in the repo I couldn't find.)

Update public filepaths to use GCP public paths

---

gnomad_qc/v3/annotations/compare_freq.py
gnomad_qc/v4/resources/basics.py

Kristen found a few places where I forgot to add a `raise` for errors. This small PR fixes those.

small error fixes

---

gnomad_qc/v3/annotations/compare_freq.py
gnomad_qc/v4/resources/annotations.py
gnomad_qc/v4/resources/basics.py
gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/platform_inference.py
gnomad_qc/v4/sample_qc/sex_inference.py

This PR is waiting on a change to the Hail sex imputation script and it relies on this gnomad_methods branch https://github.com/broadinstitute/gnomad_methods/tree/jg/sex_ploidy_variants, but I figured it was worth getting in one round of review while waiting if possible.

Add v4 sex inference script

---

gnomad_qc/v4/sample_qc/platform_inference.py

There were a few updates I needed to make for the platform PCA script to run on the full dataset.

Platform runtime updates

---

gnomad_qc/v4/resources/sample_qc.py

Small PR to fix two qc mt paths. The files will need to be moved before the PR is merged.

Fix qc mts paths typos

---

gnomad_qc/v3/resources/basics.py
gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/generate_qc_mt.py
gnomad_qc/v4/sample_qc/hard_filters.py

Currently it just filters the full datasets to the first 20 partitions

Modify generate QC MT test to use v3 and v4 test datasets

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/generate_qc_mt.py
gnomad_qc/v4/sample_qc/hard_filters.py

Accidentally closed the other PR without actually having any of these changes

Add joint QC meta HT for relatedness and population inference

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/hard_filters.py

Wenhan, I'm not positive that I have the filtering right. I added the DP filter, but I wasn't sure if that filter ended up in the final script that you ran.

Add contamination estimate computation to hardfilters

---

gnomad_qc/v4/subset.py

Adding callstats for the subset to meet a new v4 subset request.

Add callstats to v4 subset script

---

gnomad_qc/v4/sample_qc/sex_inference.py

Note: This PR is stacked on https://github.com/broadinstitute/gnomad_qc/pull/269 so https://github.com/broadinstitute/gnomad_qc/pull/269 should be reviewed first

Add option to filter high coverage intervals using DP over 0

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/sex_inference.py

Note: This PR is stacked on https://github.com/broadinstitute/gnomad_qc/pull/272 so https://github.com/broadinstitute/gnomad_qc/pull/272 should be reviewed first

Add write and read of ploidy cutoff json for sex karyotype annotation

---

gnomad_qc/v4/sample_qc/hard_filters.py
gnomad_qc/v4/sample_qc/sex_inference.py

Note: This PR is stacked on https://github.com/broadinstitute/gnomad_qc/pull/273 so https://github.com/broadinstitute/gnomad_qc/pull/273 should be reviewed first
It also depends on gnomad_methods PR: https://github.com/broadinstitute/gnomad_methods/pull/484
which depends on this PR in Hail: https://github.com/hail-is/hail/pull/12195

Modify sex inference to use precomputed interval coverage MT

---

gnomad_qc/v4/sample_qc/relatedness.py

To fix the failure described here: https://github.com/broadinstitute/gnomad_qc/pull/252#pullrequestreview-1148291734

Add --service-account parameter to cloud_batch_submit.py invocation

---

gnomad_qc/v3/resources/basics.py

Add `get_gnomad_v3_vds` and modify `get_gnomad_v3_mt`

Fix gnomAD v3 basics resource code to load VariantDataset instead of sparse MatrixTable

---

gnomad_qc/v4/resources/basics.py
gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/generate_qc_mt.py
gnomad_qc/v4/sample_qc/relatedness.py
requirements.txt

Also cleans the script up a bit

Add IBD and pc-relate to relatedness

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/assign_ancestry.py
gnomad_qc/v4/sample_qc/relatedness.py

This was in my other PR, but I think it makes sense to get it in before that one.

Simplify related samples to drop and ranking resources

---

gnomad_qc/v3/resources/annotations.py

Add Versioned Table Resource for VRS Annotations for v3 - adding to end of  gnomad_qc/v3/resources/annotations.py

Add the Versioned Table Resource for vrs_annotations

---

gnomad_qc/v3/annotations/compare_freq.py
gnomad_qc/v3/annotations/generate_freq_data.py
gnomad_qc/v3/create_release/create_release_sites_ht.py
gnomad_qc/v3/create_release/prepare_vcf_data_release.py
gnomad_qc/v3/resources/annotations.py
gnomad_qc/v4/resources/annotations.py

Updates the v3 code to use the new gnomad_method global dictionaries instead of previously used lists. This PR depends on https://github.com/broadinstitute/gnomad_methods/pull/519

Update to use global version dictionaries

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/hard_filters.py
gnomad_qc/v4/sample_qc/outlier_filtering.py

- I modified the code to use the PipelineResourceCollection to clean up the main function 
- Changed to include an option for filtering `r_ti_tv_singleton` filtering to only samples with `n_singleton` > median `n_singleton`
- Removed use of releasable samples in only the regression, moving to a full include or exclude of releasable samples

Outlier detection changes after analysis

---

gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht.py
gnomad_qc/v4/sample_qc/outlier_filtering.py

I also noticed we needed additional global annotations on the outlier detection HTs so I added them to this PR as well

Fix sample QC metadata HT to include hard-filter cutoffs in the globals

---

gnomad_qc/v4/resources/variant_qc.py
gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht.py

We need to make sure these are included in variant QC so it's easiest to have an annotation on the metadata HT for them.

Add test sample annotation to metadata HT

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht.py

Waiting on finalizing sample QC meta, but getting this in so it's ready to go ASAP.

Add global descriptions to sample QC metadata HT

---

gnomad_qc/v3/annotations/generate_sv_hists.py
gnomad_qc/v3/resources/annotations.py
gnomad_qc/v3/resources/basics.py

This script is to generate SV age and GQ histograms. I am currently blocked on testing, awaiting file access.

Script to generate v3 sv hists

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
gnomad_qc/v4/resources/annotations.py

put the validity check step (count if variants are correctly annotated as in "protein-cding" biotype) right after run_vep.

add validity step for VEP after running VEP

---

gnomad_qc/v4/resources/constants.py
gnomad_qc/v4/resources/release.py

Needed for [PR](https://github.com/broadinstitute/gnomad-constraint/pull/10) in gnomad-constraint

Add v4 coverage resource

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py
gnomad_qc/v4/resources/annotations.py

Add one module to remove missing fields from VEP105 annotation HT.
Made some minor changes in annotation resources to include both exomes and genomes.

module to remove missing fields from VEP105 HT

---

gnomad_qc/v3/annotations/vrs_annotation_batch_v3.py
gnomad_qc/v4/annotations/vrs_annotation_batch.py

The following changes needed for the move: 
1. since tgg_methods can't be installed / imported, we copied the init function to the beginning of the script; 
2. deleted unused imports

Move VRS annotation batch script from tgg_methods to gnomad_qc/v3

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/identify_trios.py
gnomad_qc/v4/sample_qc/interval_qc.py

Tests will fail until [this](https://github.com/broadinstitute/gnomad_methods/pull/564) PR is merged.

Add filter to same platform trios and use of interval QC for computing `n_mendel`

---

gnomad_qc/v3/annotations/generate_qc_annotations.py
gnomad_qc/v4/annotations/generate_variant_qc_annotations.py

Needs [this](https://github.com/broadinstitute/gnomad_methods/pull/560) PR to go in first

Switch to use `INFO_AGG_FIELDS` 

---

gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py

As written, the dictionary becomes a list of tuples but we need this to be a dictionary for frequency array access.

Make tuples a dictionary

---

gnomad_qc/v4/annotations/Dockerfile_vrs084_v4

Create a complete docker images with the 3 changes compared to the original Dockerfile:
1. use install GCS connector from broad.io
2. install bgzip
3. put gnomad & gnomad_qc dependencies inside the docker image

update VRS docker file under v4

---

gnomad_qc/v4/annotations/generate_freq.py
gnomad_qc/v4/resources/annotations.py

Just some clean-up. I want to do some more testing tomorrow, but figured I would get this back to you in the meantime.

UKB downsampling frequency PR suggestions

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
gnomad_qc/v4/resources/annotations.py

Also fixes issue of adj annotation for trio stats and changes annotation HT to allow for easy comparison of info methods

Changes needed during compute info runtime

---

gnomad_qc/v4/resources/variant_qc.py
gnomad_qc/v4/variant_qc/random_forest.py

Copy random_forest.py into v4/variant_qc/ and then get it working on gnomAD v4

Create random_forest.py for gnomAD v4 and make it functional

---

gnomad_qc/v4/resources/annotations.py

- Change to use path output after removing duplicate UKB samples from split VDS

Update split VDS path

---

gnomad_qc/v4/resources/basics.py

Noticed this problem when making the split VDS for frequency

Change v4 VDS loading function to always remove UKB samples with exact same 's'

---

gnomad_qc/v4/annotations/Dockerfile_vrs084_v4

I tried to build the Docker image but haven't pushed yet, I want to have Steve look over it since he taught us some great tricks. If it looks good, I will push it to the registry and run a test on VRS to make sure it's working.

VRS docker: update Hail to 0.2.122 and reorder the caching layers

---

gnomad_qc/v4/annotations/insilico_predictors.py

addressed review suggestions from #391 and restructured the code a bit.

function to process REVEL scores

---

gnomad_qc/v4/annotations/generate_freq.py
gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py
gnomad_qc/v4/resources/annotations.py

I still need to add some additional documentation, but wanted to get it back to you to start looking over

v4 create release suggestions and addition of compute AN

---

gnomad_qc/v4/annotations/compute_coverage.py

Depends on gnomad_methods PR https://github.com/broadinstitute/gnomad_methods/pull/615
Should probably change the output somehow so we don't overwrite the one we already have until we confirm everything looks OK. 
Thoughts on the best thing to do for that?

Add UKB/platform stratification option to v4 coverage

---

gnomad_qc/v4/annotations/insilico_predictors.py

The tuple expression this returned was difficult to use on any table. This simplifies it by just returning a table with the max scores. I think this behavior is more in line with what we expect out of these modules.

Change return type of vep in silico predictors

---

gnomad_qc/v4/annotations/insilico_predictors.py

I renamed all the files to have consistent info and format but I forgot to update the code, and I added the new variants from v4 genomes.

update CADD input file names

---

gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py
gnomad_qc/v4/resources/sample_qc.py

Function copied from this PR: https://github.com/broadinstitute/gnomad_qc/pull/390 
This contains the function for updating the v4 genomes metadata.
The first commit is basically a copy from the above PR, and any commits after that are my suggested changes.
Requires https://github.com/broadinstitute/gnomad_methods/pull/620

HGDP + 1KG update metadata

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
gnomad_qc/v4/resources/annotations.py
gnomad_qc/v4/variant_qc/final_filter.py

Still a few TODOs relating to VQSR models, but ready for the first pass of review in the meantime.
There is not really any difficult logic in this script, it's mostly just rearranging/renaming annotations and adding the filters and a couple flags.

Add script to create the final variant QC HT

---

gnomad_qc/v4/annotations/insilico_predictors.py

The initial run failed, so I added this to make it faster.

Improve CADD run by adding new_temp_file

---

gnomad_qc/v4/annotations/insilico_predictors.py

This was already run, so I don't have the raw bigwig or bedgraph anymore, I can redownload and convert it later, so with this code, you can't run a test, but the result file is already transferred to the bucket as other in silico predictors.

add function to create Phylop score

---

gnomad_qc/v4/variant_qc/import_variant_qc_vcf.py

with indel_features and snp_features in global annotations

Add Indel_ and Snp_Features to Global Annotations in import_variant_qc_vcf.py

---

gnomad_qc/v4/resources/variant_qc.py
gnomad_qc/v4/variant_qc/evaluation.py
gnomad_qc/v4/variant_qc/final_filter.py
gnomad_qc/v4/variant_qc/import_variant_qc_vcf.py
gnomad_qc/v4/variant_qc/vqsr.py

A few changes just to get import_variant_qc_vcf.py actually running for release. Added a few args and had to move VQSR_Features - I was getting an absolutely bizarre 'circular import' error ??
How it looks here is how it's running now

Changes to some VQSR Imports & Args

---

gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py
gnomad_qc/v4/resources/annotations.py

Functions copied from this PR: https://github.com/broadinstitute/gnomad_qc/pull/390
This contains the function required to make the final frequency HT for the v4.0 genome release.
The first commit is basically a copy from the above PR, and any commits after that are my suggested changes.

HGDP + 1KG update release call stats

---

gnomad_qc/v4/annotations/generate_freq_genomes.py

I added some docstring at the beginning and removed a function for VEP missing fields that will be in `gnomad_qc/v4/create_release/create_release_utils.py`

refactor genomes freq script under annotations

---

gnomad_qc/v4/annotations/generate_freq_genomes.py

In this PR: 
1. change the chrX test gene to a gene in X nonPAR region to make sure the AN computation is correct; 
2. set downsampling struct to all NA for new variants
3. add age distribution in frequency global
4. merge variant qual_hists and  age_hists from v3.1 release HT to the freq_ht.

A few add-ons to v4.0 genomes freq_ht

---

gnomad_qc/v4/variant_qc/import_variant_qc_vcf.py
gnomad_qc/v4/variant_qc/vqsr.py

No rush on this since we use the split HT

Small fixes to the VQSR loading script to correctly make the unsplit HT

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

Question: why do we use "outer" when it says "inner join"?

Add data_type for combined FAF

---

gnomad_qc/v4/create_release/create_release_sites_ht.py

Add sib singletons to release

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py
gnomad_qc/v4/resources/release.py

This adds genomes to the v4 validity check script. There is a hardcoded test path and commented out code that I'll delete and restore once this is ready but leaving this here for easy testing.

Add genomes to v4 validity checks

---

gnomad_qc/v4/create_release/create_release_sites_ht.py

Adds datatype to the initial release run path.

Add datatype to initial release_path use

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

- Fix to getting the correct index for the grpmax.faf95
- Fix to prevent mem errors when trying to convert to a pandas dataframe from Hail
- Add options for what stats to include on the release combined FAF Table

Runtime combined FAF changes

---

gnomad_qc/v4/annotations/generate_freq_genomes.py

The final run was only successful when we changed this to True.

set set_negatives_to_zero=True for the final v4 genomes freq run

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

Dependent on this PR: https://github.com/broadinstitute/gnomad_methods/pull/635

Add set female Y metrics to NA to combined faf

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
gnomad_qc/v4/create_release/create_release_sites_ht.py

- Add naive_coalesce to release Table output
- Set XX Y metrics to NA for joint_faf

A few more changes for the release

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

Expects a freq struct not faf, so move up to apply to freq before faf is made

Combined freq set Y to None earlier before faf is made

---

gnomad_qc/v4/annotations/generate_freq_genomes.py

I copied the changes you made for the merge_arrays and update how we use get `downsamplings`, test worked.

suggestions to use DOWNSAMPLINGS in the v3 freq_meta

---

gnomad_qc/v3/utils.py
gnomad_qc/v4/annotations/generate_freq_genomes.py
gnomad_qc/v4/create_release/create_release_sites_ht.py
gnomad_qc/v4/resources/annotations.py

We need to rerun the hotfix because the current v3_1_GT was already adjusted for adj

Make HGDP + 1KG use the exact same methods as those used for the v3.1.2 release HT frequency

---

gnomad_qc/v4/annotations/generate_freq_genomes.py
gnomad_qc/v4/create_release/create_release_sites_ht.py

Also fix the grpmax on the genomes freq

Fix create release to get correct globals

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

Fixes the filter intervals call

Filter intervals fix

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
gnomad_qc/v4/create_release/create_release_sites_ht.py
gnomad_qc/v4/resources/annotations.py
gnomad_qc/v4/resources/release.py

Run of the combined faf with filters is described [here](https://app.zenhub.com/workspaces/gnomad-5f4d127ea61afc001d6be50b/issues/gh/broadinstitute/gnomad_production/1256)

Add filter option to combined faf to exclude variants that will be filtered in the release HT creation

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

Missed passing datatype to release vcf path

---

gnomad_qc/v4/create_release/create_custom_liftover.py
gnomad_qc/v4/create_release/create_false_dup_liftover.py
gnomad_qc/v4/resources/release.py

Create a script to read in the v2 liftover table, v4 exome ht, and v4 genome ht, and annotate the v2 liftover table with v4 frequencies for only 3 clinically relevant genes (which lack good coverage in v4).

Create script to create custom liftover file for 3 relevant genes 

---

gnomad_qc/v3/resources/basics.py
gnomad_qc/v4/annotations/compute_coverage.py
gnomad_qc/v4/annotations/fix_freq_an.py
gnomad_qc/v4/resources/annotations.py
gnomad_qc/v4/resources/constants.py

Depends on this [PR](https://github.com/broadinstitute/gnomad_methods/pull/677)

Add all sites AN and qual stats computation for v4.1 genomes

---

gnomad_qc/v4/annotations/compute_coverage.py
gnomad_qc/v4/annotations/fix_freq_an.py
gnomad_qc/v4/resources/release.py

You can see the genomes TSV output here: gs://gnomad/release/4.1/tsv/genomes/gnomad.genomes.v4.1.allele_number.tsv.bgz

Add all sites AN export to TSV

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
gnomad_qc/v4/resources/annotations.py
gnomad_qc/v4/resources/constants.py
gnomad_qc/v4/resources/variant_qc.py

Right now all the histograms are at the top level, do you think we should add some structure?
```
----------------------------------------
Global fields:
'genomes_freq_meta': array<dict<str, str>> 
'genomes_freq_meta_sample_count': array<int32> 
'genomes_faf_meta': array<dict<str, str>> 
'exomes_freq_meta': array<dict<str, str>> 
'exomes_freq_meta_sample_count': array<int32> 
'exomes_faf_meta': array<dict<str, str>> 
'joint_freq_meta': array<dict<str, str>> 
'joint_freq_index_dict': dict<str, int32> 
'joint_faf_meta': array<dict<str, str>> 
'joint_faf_index_dict': dict<str, int32> 
'joint_freq_meta_sample_count': array<int32> 
'versions': struct {
exomes: str, 
genomes: str
} 
----------------------------------------
Row fields:
'locus': locus<GRCh38> 
'alleles': array<str> …
```

Add use of all sites AN and qual hists to joint exome genome freq/faf for v4.1 changes

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

I needed to make some modifications to get the stats to run without memory errors.
This PR also includes:
- Setting NaN values to NA for the stats
- Not running the stats test if AN is 0 for either the exomes or genomes
- Remove faf95 from grpmax if it exists

Add option to run a single chromosome for stats tests

---

gnomad_qc/v4/annotations/compute_coverage.py

Job: 26b81963ebd84a9498a55bb4c46debc6

Add region flags to exomes all sites AN

---

gnomad_qc/v4/plots/sample_growth.R

This is to add the R plot code for the sample growth from exac, v2, v3 to v4 in the repo.

Add sample growth plot R script to repo

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

Where possible we should adapt a script instead of copying it and changing it. I started modifications to the validate_and_export_vcf.py to work with data_type="joint" so it is easier to see what changes actually need to be made to work with the joint VCF. It's not done, but you can take it from here

Validate joint ht suggestions

---

gnomad_qc/v4/create_release/export_joint_vcf.py

This is for now only checking the missingness.

Add validate check to joint HT before vcf export

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

This adds some options to preparing and unfurling so we can add the data_type where it was in v4.0. The actual prep ht for export is not yet complete but it would be good to review the changes I made to the validation code so we can get that running.

Updates to validation and export for joint naming

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

Test run: b08870cb9260410596f703ce880784d3

Create a unionized p-value for freq comparison

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

This is to add the newly added struct to the unfurling.

Add stat_union in freq_comparison_stats

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

Test run job: 33f33c3dda7d40418d86e081361688f3

Add filters to combined frequency HT

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
gnomad_qc/v4/create_release/validate_and_export_vcf.py

- Fix POPS to use correct pops for genomes
- Change filters handling for exomes and genomes when data_type==joint

Fixes to validate joint release HT

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
gnomad_qc/v4/create_release/validate_and_export_vcf.py

Test: eff2565dc9634e70a7166948cf1ca5c7
It would need a fix for ordering, but just a proposal

Change the renaming of joint validate HT fields for VCF

---

gnomad_qc/v3/resources/basics.py
gnomad_qc/v4/assessment/calculate_per_sample_stats.py
gnomad_qc/v4/resources/assessment.py
gnomad_qc/v4/resources/basics.py

- Adds adj filtering
- Changes to use frequency instead of recomputing allele counts
- Change VDS loading functions to support variant filtering prior to splitting the VDS
- Split out the filtering group HT generation into it's own step so it doesn't need to be done repeatedly

Fixes to per sample summary stats

---

gnomad_qc/v4/assessment/calculate_per_sample_stats.py

Add data_type parameter so it will work on genomes. 
Test: [51fc7def2cee490f84bf060ed1018fcb](https://console.cloud.google.com/dataproc/jobs/51fc7def2cee490f84bf060ed1018fcb?region=us-central1&project=broad-mpg-gnomad)

Small changes in agg function to make it work for per-sample stats on genomes

---

gnomad_qc/v3/resources/basics.py
gnomad_qc/v4/annotations/compute_coverage.py
gnomad_qc/v4/resources/basics.py

These minor changes were made during runtime of the genomes summary stats

Small modifications to v4 genomes loading to work in summary stats code

---

gnomad_qc/v5/data_ingestion/create_vds.py

Adds in ability to pass VDS to combiner. I tested this with this file 
`gs://gnomad-mwilson/v5.0/dragen_gvcfs/dragen_vdses.txt`

Add VDS option in create_vds

---

gnomad_qc/v4/assessment/calculate_per_sample_stats.py
gnomad_qc/v4/resources/assessment.py

Dependent on: https://github.com/broadinstitute/gnomad_methods/pull/732
Exomes test: [0273acdc826c46c08ad4cd87b7b2fc6c](https://console.cloud.google.com/dataproc/jobs/0273acdc826c46c08ad4cd87b7b2fc6c/monitoring?region=us-central1&project=broad-mpg-gnomad)
Genomes test: [34a445dd3d714c9987f0e08833053890](https://console.cloud.google.com/dataproc/jobs/34a445dd3d714c9987f0e08833053890/monitoring?region=us-central1&project=broad-mpg-gnomad)

Add rare variant mode argument option and grpmax filtering

---

gnomad_qc/v5/sample_qc/relatedness.py
gnomad_qc/v5/sample_qc/relatedness_01_cuKING_dsub_setup.ipynb

PR fixes minor typos missed in printing cuKING command, updates default machine type, and adds notebook used to set up dsub

Fix print cuKING command

---

gnomad_qc/v4/subset.py

Missed adding in the filter change loci option. I also dropped a leftover print statement and added the ability to name the subset file itself.

v4 subset fix sparse split multi filter changed loci

---

gnomad_qc/v5/sample_qc/outlier_filtering.py

Add arg to toggle quiet init to see if it helps with AoU egress

Add quiet init to Hail
