broadinstitute/gnomad_qc

variant_qc/prepare_data_release.py
variant_qc/variantqc.py

1. Drop `rf_prediction` as it is generated based on 0.5 threshold
2. Make `rf_probablity` a float (using the "TP" class) rather than a Dict.

 cleaning of rf annotations in the final RF filtering files:

---

.github/workflows/ci.yml

Run Pylint on pull requests and pushes to master.
This is expected to fail since there are some issues currently in master. That won't block PRs though, because branch protection rules are not configured to require this check.

Setup GitHub Actions to run Pylint

---

.github/workflows/ci.yml
.pylintrc
lint
requirements.txt

Most directories are not set up as packages, so `pylint gnomad_qc` was not checking all files.

Lint all files

---

gnomad_qc/v3/resources/sample_qc.py
gnomad_qc/v3/sample_qc/sample_qc.py

Small PR. Added picard metric filtering to sample_qc and the HT to resources. The thresholds for each metric are the same from v2. Sample callrate is not included but I can add it in. Since this would require a densify, we could use a similar approach to what KC did in UKBB: https://github.com/macarthur-lab/ukbb_qc/blob/d8fcc39342f9e203db3a7972bec688a236b1931e/ukbb_qc/utils/sparse_utils.py#L16

Add picard filters to sample_qc

---

gnomad_qc/v3/annotations/generate_qc_annotations.py

Added changes to info creation including adding pab_max and AS_lowqual, fixing error Tim found, and using the common repo for info splitting. It is still failing pylint because there is no `slack_creds` so `from gnomad_qc.slack_creds import slack_token` doesn't work. This was the way that KC and I added in for UKBB to use the new `slack_notifications` module. I'm not sure of the best option, maybe add a `slack_creds.py` with an empty string for `slack_token` then each of us can modify it and print an error message if it's empty.

Fix info ht

---

gnomad_qc/v3/resources/variant_qc.py
gnomad_qc/v3/variant_qc/evaluation.py

Notes from Nick here: https://atgu.slack.com/archives/CNE92R265/p1620940969023300
Mike's post here https://discuss.hail.is/t/initializing-hail-with-grch38-fails/2043 raises a good point. For reusable libraries, we should avoid anything that runs at import time and uses Hail because then simply importing a module will initialize Hail. And it will potentially be initialized with a different configuration than what you want to use. For that post, I think gnomad_qc/v3/resources/variant_qc.py is the culprit. Importing anything from gnomad_qc.v3.resources causes 2 tables and 2 matrix tables to be read https://github.com/broadinstitute/gnomad_qc/blob/9fc7088c6d160f8f0e8c0aea42e18d19a62d8d5c/gnomad_qc/v3/resources/variant_qc.py#L27-L38

Fix to resources so Hail isn't initialized on import

---

gnomad_qc/v3/sample_qc/sample_qc.py

Nick identified that we forgot to save the output from `filter_low_conf_regions` and therefore in the cleaned up v3 sample QC code we are not performing the centromere and telomere filter.
Note this doesn't impact v3 or v3.1. The v3 sparse MT has no centromeres and telomeres and this was the v3.1 runtime code: https://github.com/broadinstitute/gnomad_qc/blob/efea6851a421f4bc66b73db588c0eeeb7cd27539/gnomad_qc/v3/sample_qc/sample_qc.py#L67

Fix to filter centromeres and telomeres in sample QC

---

gnomad_qc/v2/annotations/generate_frequency_data.py
gnomad_qc/v2/annotations/generate_ld_data.py
gnomad_qc/v2/annotations/generate_qc_annotations.py
gnomad_qc/v2/load_data/import_gnomad_sv.py
gnomad_qc/v2/load_data/import_resources.py
gnomad_qc/v2/load_data/import_vcf.py
gnomad_qc/v2/load_data/load_coverage.py
gnomad_qc/v2/sample_qc/apply_hard_filters.py
gnomad_qc/v2/sample_qc/assign_subpops.py
gnomad_qc/v2/sample_qc/create_fam.py
gnomad_qc/v2/sample_qc/exomes_platform_pca.py
gnomad_qc/v2/sample_qc/finalize_sample_qc.py
gnomad_qc/v2/sample_qc/generate_hardcalls.py
gnomad_qc/v2/sample_qc/get_topmed_dups.py
gnomad_qc/v2/sample_qc/joint_sample_qc.py
gnomad_qc/v2/variant_qc/calculate_concordance.py
gnomad_qc/v2/variant_qc/correct_fafs.py
gnomad_qc/v2/variant_qc/create_ranked_scores.py
gnomad_qc/v2/variant_qc/make_var_annot_hists.py
gnomad_qc/v2/variant_qc/select_qc_set.py
gnomad_qc/v2/variant_qc/variantqc.py

After https://github.com/broadinstitute/gnomad_methods/pull/404, Pylint now notices these broken imports.
This replaces the old `try_slack` function with the newer [`slack_notifications`](https://broadinstitute.github.io/gnomad_methods/api_reference/utils/slack.html#gnomad.utils.slack.slack_notifications).

Replace try_slack function in v2 scripts

---

gnomad_qc/v4/resources/basics.py
gnomad_qc/v4/sample_qc/hard_filters.py

We need to split after the filter sample calls if we want to use the remove_dead_alleles parameter. I also removed the test return. I know there are 0 samples removed, but I would have caught the split error on testing.

Fix to basic resources to split after sample filtering of UKBB samples

---

gnomad_qc/v3/analysis/vary_subpop_params.py

reannotating with subpop_description will undo the manual curation done in assign_pops, so switching to using training_pop

subpop_description to training_pop

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/sex_inference.py

Note: this PR is stacked on #266 and should be reviewed after #266
Moving this outside the `compute_sex` function allows us to reuse these computations rather than redo them each time we need to run the `compute_sex` function.
Also:
- Cleans up main by moving the platform HT loading into a function.
- Renames `high_cov_by_platform_all` -> `high_cov_all_platforms`

Split out interval coverage and interval QC for sex inference from the main `compute_sex` function

---

gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/sex_inference.py

Note: This PR is stacked on #267 so #267 should be reviewed first. This is also dependent on parameterizing karyotype assignment in the `gnomad_methods`: https://github.com/broadinstitute/gnomad_methods/pull/478
This cleans up the code and also makes it easy to later re-annotate karyotype using different cutoffs if we need to.

Split `compute_sex` into two steps: ploidy imputation and then karyotype sex inference

---

gnomad_qc/v4/sample_qc/sex_inference.py

Note: This PR is stacked on https://github.com/broadinstitute/gnomad_qc/pull/271 so https://github.com/broadinstitute/gnomad_qc/pull/271 should be reviewed first
This is a small PR to use the add options for the variant filtering, compute_x_frac_variants_hom_alt, and use of gaussian mixture model that were implemented in gnomad_methods

Add additional `annotate_sex` options

---

gnomad_qc/v4/sample_qc/hard_filters.py

Need to check that sample has defined sex_karyotype to determine `sex_aneuploidy` filter

Small runtime fix to hard filtering with sex imputation

---

gnomad_qc/v4/sample_qc/relatedness.py

Note: requires a fairly recent Google Cloud SDK (`gcloud`) installation.

Write a _SUCCESS file to the relatedness Parquet output directory

---

gnomad_qc/resource_utils.py
gnomad_qc/v4/sample_qc/outlier_filtering.py

When finalizing the outlier QC HT the globals for "qc_metrics_stats" and "lms" need to be filtered to only the stats requested

Remove unused final outlier QC stats

---

gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht.py

bi-allelic sample QC was used for hard-filtering, this PR includes it in the sample QC metadata HT

Add bi-allelic sample QC to metadata HT

---

gnomad_qc/v3/annotations/generate_sv_hists.py

The SV team repurposes the rsid field to be a unique identifier. This adds the field into the output for use by the browser team.

Add rsid to SV hist output

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
gnomad_qc/v4/resources/annotations.py
gnomad_qc/v4/resources/basics.py

Add computation of allele counts to be done by the default_compute_info` in gnomad_methods instead of as an additional pipeline step.

Variant QC allele counts 

---

gnomad_qc/v3/annotations/generate_qc_annotations.py

1. remove` action="store_true"`, because it can't be used with `default="101"` together. It caused error:
`generate_qc_annotations.py: error: argument --vep_version: ignored explicit argument '105'`
2. since sparse MatrixTable was deleted (to save space), VEP will run on VariantDataset, it's better we change the code to get v3 vds directly. 
3. add a tmp_dir to hl.init for a faster I/O and potentially avoid disk space or Docker error.

delete action method in vep_version argument & change input for VEP to raw VDS

---

gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py

This function is used to rename ancestry group fields to match v4 exomes.
Which means that all "oth" will be changed to "remaining".
2 Global fields are renamed: freq_meta (in the values of key "pop") and freq_index_dict (in the keys).

replace 'oth' with remaining in Global fields of v4 genomes HT

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py

I ran the test dataset using:
```
hailctl dataproc submit jg2 gnomad_qc/v4/annotations/generate_variant_qc_annotations.py --test-dataset --compute-info --split-info
```
Output:
gs://gnomad-tmp/gnomad_v4.0_testing/annotations/exomes/gnomad.exomes.v4.0.info.ht
gs://gnomad-tmp/gnomad_v4.0_testing/annotations/exomes/gnomad.exomes.v4.0.info.split.ht
Test notebook: gs://gnomad-julia/gnomad_v4/test_allele_specific_annotation_correction.ipynb
Test HTML: gs://gnomad-julia/gnomad_v4/test_allele_specific_annotation_correction.html

Add fix to allele specific annotations that are longer than LA

---

gnomad_qc/v4/annotations/vrs_annotation_batch.py

Dan suggested us to delete this redundant part of listing.

VRS: delete listing with hadoop before import_vcf

---

gnomad_qc/v4/annotations/Dockerfile_vrs084_v4

The Java 8 from adoptopenjdk is deprecated.
https://adoptium.net/blog/2023/07/adoptopenjdk-jfrog-io-has-been-deprecated/
We have to update to a new source for the installation. 
We have to install Hail 0.2.120 or later for faster hadoop listing. 
Waiting on Hail 0.2.121's release in early September so we don't have to wait for a long time for an error in Hail Batch. 
Two issues related to our Batch run: https://github.com/hail-is/hail/pull/13500 & https://github.com/hail-is/hail/issues/13502

update Java 8 installation resource  and Hail version

---

gnomad_qc/v4/annotations/generate_freq.py
gnomad_qc/v4/resources/annotations.py

Misnamed the branch but this adds the non_ukb subset downsamplings as well as a couple other things, like the try, finally to copy the log on OOM failures, and also the freq_meta_sample_count to the globals. I opted for doing another pass through the data instead of adding more strata to the initial pass as it would almost double our aggregations and I figured we may end up with the 137 again. This extra pass was also discussed in slack back in May before we know how much more work freqs would be so I figured it was the preferred approach. This also prevents changes to  the gnomad_methods build strata and annotate_freq functions. The way the freq_meta is updated, adding the subst key, may change in another round since I need to annotate the subset frequencies onto the main freq table …

non_ukb downsamplings for v4 freq

---

.pylintrc

I think this will fix our current pylint failures. I think it'sthe right behavior -- we don't want to be linting a repo we don't own.

Add cuKING to ignore-paths

---

gnomad_qc/v4/annotations/vrs_annotation_batch.py

Set driver_memory to 'highmem' to avoid out of memory error in Hail Batch run.

change driver_memory to highmem in hl.init

---

gnomad_qc/v4/annotations/vrs_annotation_batch.py

We still need -- for hailctl batch submit, so I removed the note.

remove a note about command

---

gnomad_qc/v4/annotations/generate_freq.py

This finalizes the freq HT. It renames the original and  adjusted freq annotations. It also drops any 'gatk_version' index from freq_meta, freq, high_ab_hets_by_group, pre_adjusted_freq, and freq_meta_sample_count. For now this stores the pre_adjusted freq but I'm wondering if we need to here since we currently have the preadjustment HT. If we want all the information in one place, we would need to store the preadjustment histograms as well so I will need to add that in. Alternatively, if we plan on keeping the full preadjustment HT around, I'm not sure we need the predajustment/high AB hets on this table but it was in the functions docstring todo placeholder so I left it for now.

Finalize freq HT

---

gnomad_qc/v4/annotations/generate_freq.py

For any site with an adj AF of NA, the script was setting all fields to NA. This came down to the hl.if_else statement on the AF threshold -- If the conditional in hl.if_else is missing (AF[0] is often NA), everything got set to NA which was very unexpected but I guess NA is just that. I'll rerun the combine, adjustment, and finalize step of freq once this and the [merge_histogram bug](https://github.com/broadinstitute/gnomad_methods/pull/614) go in.

Fix the NA bug in frequency adjustments

---

gnomad_qc/v4/annotations/insilico_predictors.py
gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py

In this PR, I removed the nested structs for insilico predictors, add the bug-fixed rerun for v4 genomes in Pangolin, most importantly, I put in a function to process SIFT and PolyPhen scores, I also started to organize the steps/to-dos to create v4 genome release. 
I also put the function in create_release code, because I want this to run as a pipeline.

process SIFT and PolyPhen scores from vep_ht

---

gnomad_qc/v4/annotations/generate_freq.py

This adds in the genetic ancestry group with the highest FAF per threshold and its value. This is different than grpmax which grabs the genetic ancestry group with the highest AF, and then also annotates its FAF. Highest AF does not equal highest FAF.

Add gen_anc_faf_max

---

gnomad_qc/v4/annotations/generate_freq.py

I made `generate_freq_group_membership_array` return a place holder for the raw genotype because it was too confusing having it be a different length than the globals. I know this might not be run again ever, but wanted to make sure it works

Small change to work with updated `generate_freq_group_membership_array`

---

gnomad_qc/v4/create_release/create_release_sites_ht_genomes.py
gnomad_qc/v4/resources/sample_qc.py

Starting to get in functions from this PR: https://github.com/broadinstitute/gnomad_qc/pull/390 in a more modular way. 
This contains the functions for determining related HGDP + 1KG samples to other v3 or v4 release samples and should therefore not be added to the v4 genome set.
The first commit is basically a copy from the above PR, and any commits after that are my suggested changes.

Add HGDP +  1KG functions to determine relatedness to nonsubset and v4 duplicates

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
gnomad_qc/v4/resources/annotations.py
gnomad_qc/v4/resources/release.py
requirements-dev.txt

This is based on Julia's PR #403 with some changes to use the freq_ht instead of release_ht, calculate faf and grpmax when it's not present in the prefixed freq_ht, rename the popmax to grpmax for v4, and test on one gene: PCSK9 (chr1:55039447-55064852).

Script to compute combined FAF of v4 genomes and exomes

---

gnomad_qc/v4/annotations/Dockerfile_vrs084
gnomad_qc/v4/annotations/vrs_annotation_batch.py

I added the options to launch the batch code on either exomes or genomes vep_ht input, but as of Hail 0.2.122, Hail Batch seems still flaky to run on >100k partitions, I tried on genomes but it failed, so I changed the code a bit to use input and output paths as we want. 
I also put the versions in globals.

Make VRS batch code more general on input and output

---

gnomad_qc/v4/resources/basics.py
gnomad_qc/v4/resources/meta.py
gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht.py
gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht_genomes.py

This script is used to create the sample QC metadata HT for genomes. The main updates from v3.1 to v4.0 are:
Sample QC annotations for HGDP + TGP subset, this script directly merges the updated annotations from the subset meta HT to the full meta HT.

Code to update v4 genome sample_qc metadata

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

These werent being flattened properly nor were we grabbing all the data for the VCF. They arent the prettiest implementation but grpmax has two renames within it and in order to keep the subset specific annotations together I added the for loop for the subsets.

Flatten the gnomad/non_ukb structs in fafmax and grpmax

---

gnomad_qc/v4/annotations/insilico_predictors.py

The current implementation leads to duplicate rows because the annotations and the scores are identical in mane and canonical tables. This gets around that issue by naming the annotation by table so as to not duplicate rows and then selects mane over canonical for revel_max

Get rid of duplicates in revel

---

gnomad_qc/v4/create_release/make_var_annot_hists.py
gnomad_qc/v4/resources/release.py

This adds the site quality metric histograms for v4. It is essentially a copy and paste from v3. 
v4 exome metric histogram parameters have been discussed here:  https://atgu.slack.com/archives/CRA2TKTV0/p1698085670870479 
This function will work on genomes but we will need to confirm the v4 genome ranges still look ok using the v3 ranges and then copy the file if they do, or modify it and put it in the v4 location if they need updates. 
These histograms are displayed on the variant pages and the variants specific metric gets a line added by the browser 
Exome test run here:
https://console.cloud.google.com/dataproc/jobs/a97858c504b244e3a9bb37f5e6439549/monitoring?region=us-central1&project=broad-mpg-gnomad

Add site quality histograms for v4

---

gnomad_qc/v4/sample_qc/create_sample_qc_metadata_ht_genomes.py

In v3.1, `high_quality` means means NOT `hard_filtered` and NOT `gnomad_sample_filters.qc_metrics_filters`, and it was kept in hgdp_tgp_meta as `gnomad_high_quality`, in v4.0, `high_quality` means NOT `hard_filtered` and NOT `subcontinental_pca.outlier` from the subset. So, `gnomad_high_quality` in the subset meta shouldn't be copied to the full meta. Here, I corrected this.

using high_quality instead of gnomad_high_quality from hgdp_tgp meta

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

This adds genomes to the VCF export code. The current test run will warn 
```WARNING (gnomad.assessment.validity_checks 841): faf95_grpmax in info field does not exist in VCF header!``` We plan on rerunning genomes so  faf95 is removed grpmax.

Add genome vcf export

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

There were some errors for the stats on the combined freq/faf HT that need to be fixed before we can determine if we should release these stats and/or add a flag indicating a significant deviation between the two

Fix stats on combined exomes/genomes frequencies

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

A user found that the number of v4's VCF VEP fields(48) do not match the header(46). This is a result of using default parameters in the function that creates a string out of the vep struct. The default call uses the default VEP_CSQ_FIELDS  list which contains SIFT and Polyphen. It then inserts missing values  in the "validated_ht"  after not finding the fields in the VEP annotation. This "validated_ht" is then used for VCF export. 
This PR fixes the exported VCF fields by removing SIFT and Polyphen from the `csq_fields` passed to the `vep_struct_to_csq` function, resulting in the correct number of vep fields in the VCF.

Remove sift and polyphen from VCF export

---

gnomad_qc/v4/resources/sample_qc.py

This change will give access to the pca scores, loadings, and eigenvalue files which will move to under the ancestry_inference subdirectory.

Move PCA files to under ancestry_inference

---

gnomad_qc/v4/create_release/create_release_sites_ht.py
gnomad_qc/v4/resources/release.py

We dont have an included datasets json for v4.0 genomes. This will fix that moving forward.  We ran exomes last so the existing datasets file is correct.

Pass data_type to included datasets path function

---

gnomad_qc/v3/annotations/generate_freq_data.py
gnomad_qc/v3/create_release/prepare_vcf_data_release.py
gnomad_qc/v4/annotations/generate_freq.py
gnomad_qc/v4/annotations/generate_freq_genomes.py
gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
gnomad_qc/v4/create_release/validate_and_export_vcf.py

This is to update the code to work with: https://github.com/broadinstitute/gnomad_methods/pull/658/files.
I had to change the VCF export code for v4 beyond just referencing the version since the code works for both genomes and exomes but genomes uses v3 faf pops while exomes will use v4. This is not pretty but its the least amount of code to add without major restructuring. We should probably rethink these global variables.

Update faf and popmax pops to remove to account for change in gnomad_methods

---

docs/conf.py
docs/flowcharts/v4/index.mmd
docs/generate_api_reference.py
docs/requirements.docs.in
docs/requirements.docs.txt

As of now I have only added one very simple flowchart, but others can be added to the docs/flowcharts directory to be included at the top of each sphinx documentation page.

Add support for including mermaid flowcharts at the top of the sphinx documentation

---

gnomad_qc/v4/annotations/generate_freq.py

This fixes the existing 4.0 code so all hom ref calls are kept in the subsets after the split and densify. I tried to document extensively to make sure future users knew this wasnt used in v4.0 but would have the desired  freq outcome if it were.

Add post-v4.0 freq VDS split fix to ensure all hom refs are kept in all samples

---

gnomad_qc/v4/create_release/create_release_sites_ht.py
gnomad_qc/v4/resources/constants.py

We're removing joint freq and associated field from the v4.1 release. This doesnt need too much of a code change as the script was built for adding or removing tables in the join but there was one spot where I missed flexibility beforehand, setting the final schema order. This update checks if the joined HT fields exist in the defined FINALIZED_SCHEMA and removes them from the ordering if they do not, while also throwing a warning that they are not present.

Add final release schema check

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

We need the joint fields to be optional in the checks and export since we removed them in v4.1.

Make joint optional in validate and export vcf

---

gnomad_qc/v4/create_release/create_release_sites_ht.py

Since we have decided to no longer include the joint_faf on release HTs, remove it from the default in release HT creation

Default to no joint_faf in release

---

gnomad_qc/v4/create_release/calculate_variant_statistics.py
gnomad_qc/v4/resources/temp_hail_methods.py

I simplified the two functions and renamed a few things, I added in option to get the count of missense and synonymous variants. I also prefer to write the aggregated stats in the HT globals, I think it's better structured this way. We'll discuss if only output just one final HT, but make it two steps. 
I got the same number of all_variants the same as you for 1 sample, but number of variants passing filters are not again the same, I think the new Exome release seems changed, we need to confirm with Julia for that. 
My test run is here: [bcd45e3f472b4033bfac9532a022dafe](https://console.cloud.google.com/dataproc/jobs/bcd45e3f472b4033bfac9532a022dafe?region=us-central1&project=broad-mpg-gnomad)

Suggestions to calculate variants per sample in exomes and genomes

---

gnomad_qc/v4/resources/basics.py

This adds in an option to delete an excessively multi-allelic locus on chr19 as we did in https://github.com/broadinstitute/gnomad_qc/blob/cdc3dd5b8cd3cf5e381addac96cd921d7fe604e8/gnomad_qc/v4/annotations/generate_freq.py#L258.

Remove extreme multiallelic in exomes VDS

---

gnomad_qc/v4/annotations/insilico_predictors.py

This adds in a function to create Tables with REVEL scores for variants in v4.1 release in Ensembl v105 MANE Select transcripts that are not found in REVEL (Ensembl v64).

Get REVEL score for variants in missing MANE transcripts

---

gnomad_qc/v4/create_release/create_combined_faf_release_ht.py

Changes:
1. Include "sex" in exomes and genomes faf; 
2. Add `freq_index_dict` and `faf_index_dict` in exomes and genomes globals; 
3. Fix failures on CMH test for testing (this change not working yet with Hail 0.2.128); 
4. Exclude pooled odds ratio from the stats; 
Now the joint HT is like this for faf meta:

Add sex, freq_index_dict and faf_index_dict in joint release HT

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

Changes are: 
1. Move histograms to unfurl and add data_type to renaming; 
2. Keep order in `info` while renaming.

Move quality histogram and keep order while renaming

---

gnomad_qc/v4/create_release/validate_and_export_vcf.py

This added (on top of VCF header PR #608): 
1. a function to get joint filters from exomes and genomes filters annotations; 
2. workarounds on fields that don't exist in joint HT; 
Test run: [5547c86f934e4c64af196761b1b6e41b](https://console.cloud.google.com/dataproc/jobs/5547c86f934e4c64af196761b1b6e41b?region=us-central1&project=broad-mpg-gnomad)

Modify code to export joint VCF

---

gnomad_qc/v4/analyses/grpmax_comps.py

This code generates tables by European grouping as well as the AF threshold. I'm not sold on the location of this script so thoughts welcome!

grpmax vs European AF split nonsynonymous variant analysis

---

gnomad_qc/v3/utils.py
gnomad_qc/v4/assessment/calculate_per_sample_stats.py
gnomad_qc/v4/resources/assessment.py

Cluster for all tests:
```
hailctl dataproc start jg2 \
--requester-pays-allow-all \
--packages="git+https://github.com/broadinstitute/gnomad_methods.git@main","git+https://github.com/broadinstitute/gnomad_qc.git@main" \
--max-idle 540m \
--master-machine-type n1-highmem-16 \
--worker-machine-type n1-highmem-8 \
--no-off-heap-memory 
```
Test the full pipeline on a single gene of the test dataset:
Without intermediate:
Command:
```
hailctl dataproc submit jg2 gnomad_qc/v4/assessment/calculate_per_sample_stats.py \
--data-type exomes \
--test-gene \
--test-dataset \
--create-filter-group-ht \
--create-per-sample-counts-ht \
--aggregate-sample-stats \
--autosomes-only-stats \
--pyfiles ../gnomad_methods/gnomad,gnomad_qc \
--overwrite
```
Job: …

Add option to summary stats to get around memory errors

---

gnomad_qc/example_notebooks/ancestry_classification_using_gnomad_rf.ipynb
gnomad_qc/v4/assessment/calculate_per_sample_stats.py

After merging #584, [checks](https://github.com/broadinstitute/gnomad_qc/actions/runs/10633552159/job/29478854802) failed and needed to run  ``pip install "black[jupyter]"`` and reformat these notebooks.

Reformat files after Black updated to 24.3.0

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
gnomad_qc/v4/resources/annotations.py

Update the `run_generate_trio_stats` function to filter the fam_ht to releasable trios (pat-mat-proband) only. It won't overwrite the existing output for all trios. 
**Tested:** 
5 trios from test VDS
[5650d7690333482f856e50c4105864ff](https://console.cloud.google.com/dataproc/jobs/5650d7690333482f856e50c4105864ff?region=us-central1&project=broad-mpg-gnomad)
3 releasable trios from test VDS
[f70603af341244ae81f23d868d9945c3](https://console.cloud.google.com/dataproc/jobs/f70603af341244ae81f23d868d9945c3?region=us-central1&project=broad-mpg-gnomad)

Add option to filter to releasable trios for generating trio stats

---

gnomad_qc/v4/annotations/generate_variant_qc_annotations.py

This function has been changed accordingly with this [PR](https://github.com/broadinstitute/gnomad_methods/pull/739) in gnomad_methods. 
Note: as of 2024-10-29, the Hail v0.2.133 wasn't able to run: 
```
hailctl dataproc submit trio-stats gnomad_qc/v4/annotations/generate_variant_qc_annotations.py --generate-trio-stats --releasable-trios-only --overwrite
```
on the whole dataset, I had to roll back to Hail v0.2.120, the working version that we used in September 2023 to run on all the trios.

Clean up and re-organize run_generate_trio_stats

---

gnomad_qc/v4/resources/variant_qc.py
gnomad_qc/v4/variant_qc/final_filter.py

Our original final filter table filtered out variants that are not in the release by freq_ht, we want to have non-missing filters for de novo variants (which weren't in the release because some probands were excluded due to relatedness). 
Test: [45ff85cc7538413ba0ea020cdb96f3ad](https://console.cloud.google.com/dataproc/jobs/45ff85cc7538413ba0ea020cdb96f3ad?region=us-central1&inv=1&invt=AbjExw&project=broad-mpg-gnomad)

Write a new final filter Table with all variants for de novo release

---

gnomad_qc/v3/resources/basics.py
gnomad_qc/v4/resources/basics.py

Add functionality for filter_samples_ht and naive_coalesce_partitions to the get_gnomad_v4_genomes_vds() code by way of edits to the v3 resources basics code

Add filter_samples_ht and naive_coalesce_partitions to v4 genomes VDS code

---

gnomad_qc/v4/create_release/create_de_novo_release.py
gnomad_qc/v4/resources/release.py
gnomad_qc/v4/resources/sample_qc.py
gnomad_qc/v4/sample_qc/identify_trios.py

This cleaned up some redundant dense mt functions and arguments since we had PR #651. Julia created the dense MT in job [0a3e98e75ba14b2f8341012515d11f8b](https://console.cloud.google.com/dataproc/jobs/0a3e98e75ba14b2f8341012515d11f8b?region=us-central1&inv=1&invt=AboKJg&project=broad-mpg-gnomad) before the PR was merged. 
This is waiting on [PR #760](https://github.com/broadinstitute/gnomad_methods/pull/760) in gnomad_methods. 
Test run on chr20: [b0729d42ea77466c8cc1fe9697e73af1](https://console.cloud.google.com/dataproc/jobs/b0729d42ea77466c8cc1fe9697e73af1?region=us-central1&project=broad-mpg-gnomad)

Generate de novo release

---

gnomad_qc/v5/sample_qc/merge_project_meta.py

A few updates after I realized release was a string and AoU released QC metric data for all files. The file change doesnt matter for this module but I figured better to grab the all sample file here rather than flagged samples. I also moved to a left join as the AoU SQL query was pulling age data for 600k participants but we only want srWGS sample data.

Update release to bool and aou qc metric file, release 3/27

---

gnomad_qc/v5/resources/basics.py
gnomad_qc/v5/resources/sample_qc.py
gnomad_qc/v5/sample_qc/hard_filters.py

This PR makes two main changes to improve test coverage and performance for `compute_sample_qc`:
1. Excludes a locus with extreme allele count from loading to avoid memory or runtime issues.
2. Updates test mode logic in `compute_sample_qc` to load a small genomic interval known to contain 2 loci with >100 alt alleles. This enables:
- Verifying correct behavior using `count_rows()`.
- Switching from loading all loci for 10 samples → to loading a small interval for all samples (excluding pre-filtered ones), which:
- Preserves correct sample count filtering.
- Reduces runtime in test mode (now it takes ~14 mins).
Test run in this [notebook](https://workbench.researchallofus.org/workspaces/aou-rw-4b0bd63f/gnomadproduction/analysis/preview/hard_filter_02_vds_sample_qc.ipynb). 
BTW, I tried to …

Remove loci with >100 alt alleles from vds sample QC

---

.github/CODEOWNERS
.github/dependabot.yml

Github now has a [CODEOWNERs file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) which we'll use to replace dependabot automatic assignment.

Drops deprecated reviewers from dependabot config and adds CODEOWNERs for automatic review assignment 

---

gnomad_qc/v4/resources/basics.py

The new warning regarding files moving into archive and a function updating to autoclass was surfacing through a series of imports between v5 basic resources -> v4 basic resources ->v3 basic resources.  This moves the call to v3 into the function that uses it as to not trigger the warning every time the module is accessed.

Lazy import v3 for v4s get vds function to prevent unwanted logger 

---

gnomad_qc/v4/subset.py

We no longer offer these as ukb inclusion can be incredibly costly and subset callstats are easy enough for requesters to do themselves. This cleans this script up.

Drop ukb and subset callstat support from subset requests

---

gnomad_qc/v5/sample_qc/outlier_filtering.py

- Fixes project prefix from "gnomad" > "aou"
- Sets r_ti_tv_singleton to 0 for 8 samples missing this metric
- Makes resources lists in `check_resource_existence` because those args are meant to be type `Dict[str, List]` (https://github.com/broadinstitute/gnomad_qc/blob/00855bef261ef68a43be3347d6a0ba7fc4612971/gnomad_qc/resource_utils.py#L10C27-L11C51)

Small fixes to sample QC outlier

---

requirements.txt

We previously used an indirect dependency through the ga4gh package. The ga4gh removed the markdown dependency when moving from 0.8.4 to 2.0.1 so we need to install it ourselves.  This causes the git action in gnomad_methods to fail: https://github.com/broadinstitute/gnomad_methods/actions/runs/17776527117/job/50525507592?pr=797.

Add markdown to direct dependency list

---

gnomad_qc/v5/resources/basics.py

I ran the samples to exclude and there were silent failures in the run as these expressions never wrote out. Fixed so they now do.

Fix expression write for failing metirc samples and low qual samples

---

gnomad_qc/v4/annotations/vep_context_ht.py

Test run:
```
hailctl dataproc submit vep-115-no-ancestral gnomad_qc/gnomad_qc/v4/annotations/vep_context_ht.py \
--vep-version 115 \
--test \
--pyfiles gnomad_qc/gnomad_qc,gnomad_methods/gnomad \
--project broad-mpg-gnomad
```
Job: [aa540a8ff2cc484ea98f5f8edf11a925](https://console.cloud.google.com/dataproc/jobs/aa540a8ff2cc484ea98f5f8edf11a925/monitoring?region=us-central1&project=broad-mpg-gnomad)

Add VEP 115 as an option for the VEP context script
